# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trademark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Title')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Trademarks',
                'ordering': ['name'],
                'verbose_name': 'Trademark',
            },
        ),
        migrations.AlterIndexTogether(
            name='trademark',
            index_together=set([('id',)]),
        ),
    ]
